### ISSUE TITLE
Incorrect URL under Contributing in README.md File

### ISSUE THREAD

**Issue by AkashSharma001** [HackSquadDev/discord-js#29]
## Describe the bug

When I clicked on the **issues** hyperlink under **Contributing**, I got a 404 not found error.

## To Reproduce

1. Go to 'README.md'
2. Click on 'issues' under Contributing
3. See the error

## Expected behavior

Discord-js issue page should show.

**Comment by AkashSharma001** [comment]
Please Assign me.
@TheLearneer @MrKrishnaAgarwal

**Comment by bsantosh909** [comment]
The link works completely fine to me. 🤔

**Comment by MrKrishnaAgarwal** [comment]
The link works absolutely fine 😬

**Comment by AkashSharma001** [comment]
The issue url under Contributing is:- https://github.com/HackSquadDev/discord-js/blob/main/issues
but URL should be:-
https://github.com/HackSquadDev/discord-js/issues
@TheLearneer @MrKrishnaAgarwal

**Comment by bsantosh909** [comment]
@AkashSharma001 Thank you for your concerns, but we are not looking forward for any improvements to the docs as of now 🙇

**Comment by AkashSharma001** [comment]
Okay.
@TheLearneer
