### ISSUE TITLE
package.json doesn't have description field. 

### ISSUE THREAD

**Issue by PrakashGatiyala** [HackSquadDev/discord-js#31]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/197417490-cb7f6edc-43eb-4990-898f-ec5175047729.png)

Hi, package.json doesn't have description field. 
I want to add field
 `"description": "This is a simple discord bot made with discord.js for HackSquad's discord server."` in package.json file. 

Can I work on this issue?

**Comment by PrakashGatiyala** [comment]
Why it is @MrKrishnaAgarwal  to you automatically?
Can you assign it to me?

**Comment by twlite** [comment]
This is not really important because it is not displayed anywhere. Plus the actual description is written in readme file as well as the repository description.

The description field jn package.json is for npm registry which is out of scope for this project.

**Comment by PrakashGatiyala** [comment]
Ok, No worries

**Comment by PrakashGatiyala** [comment]
Hi @archaeopteryx1 
But why it was assigned to MrKrishnaAgarwal  directly ?
is it bug ?

**Comment by twlite** [comment]
> Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?

No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml

**Comment by PrakashGatiyala** [comment]
> > Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?
> 
> No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml

I mean, When someone create a issue here, it should assigned to them or left unassigned.
Like this issue is created by me. so it should assigned to me. right ?
Like if you create a new issue. so it should assigned to you. right ?

Why him only?

![image](https://user-images.githubusercontent.com/34413515/197418282-ebffdef0-76a5-409e-b6ff-16d3d3056665.png)

**Comment by twlite** [comment]
> > > Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?
> > 
> > 
> > No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml
> 
> I mean, When someone create a issue here, it should assigned to them or left unassigned. Like this issue is created by me. so it should assigned to me. right ? Like if you create a new issue. so it should assigned to you. right ?
> 
> Why him only?

Issues arent assigned to anybody by default. But since this issue template (question) defines default person, github automatically assigns it to him.

![image](https://user-images.githubusercontent.com/46562212/197418353-b6c1ca72-ea48-4372-a2c2-6b543027fcb0.png)

**Comment by PrakashGatiyala** [comment]
> > > > Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?
> > > 
> > > 
> > > No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml
> > 
> > 
> > I mean, When someone create a issue here, it should assigned to them or left unassigned. Like this issue is created by me. so it should assigned to me. right ? Like if you create a new issue. so it should assigned to you. right ?
> > Why him only?
> 
> Issues arent assigned to anybody by default. But since this issue template (question) defines default person, github automatically assigns it to him.

Should I remove default person? Because It is not good have default person for every issue.

**Comment by twlite** [comment]
> > > > > Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?
> > > > 
> > > > 
> > > > No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml
> > > 
> > > 
> > > I mean, When someone create a issue here, it should assigned to them or left unassigned. Like this issue is created by me. so it should assigned to me. right ? Like if you create a new issue. so it should assigned to you. right ?
> > > Why him only?
> > 
> > 
> > Issues arent assigned to anybody by default. But since this issue template (question) defines default person, github automatically assigns it to him.
> 
> Should I remove default person? Because It is not good have default person for every issue.

Issues that go under questions category is assigned to @MrKrishnaAgarwal 

Create an issue under feature req category for example in order to have no assignees.

**Comment by PrakashGatiyala** [comment]
> > > > > > Hi @archaeopteryx1 But why it was assigned to MrKrishnaAgarwal directly ? is it bug ?
> > > > > 
> > > > > 
> > > > > No it is not. See https://github.com/HackSquadDev/discord-js/blob/main/.github/ISSUE_TEMPLATE/other.yml
> > > > 
> > > > 
> > > > I mean, When someone create a issue here, it should assigned to them or left unassigned. Like this issue is created by me. so it should assigned to me. right ? Like if you create a new issue. so it should assigned to you. right ?
> > > > Why him only?
> > > 
> > > 
> > > Issues arent assigned to anybody by default. But since this issue template (question) defines default person, github automatically assigns it to him.
> > 
> > 
> > Should I remove default person? Because It is not good have default person for every issue.
> 
> Issues that go under questions category is assigned to @MrKrishnaAgarwal
> 
> Create an issue under feature req category for example in order to have no assignees.

Agree, But that is not good practice  though.

**Comment by twlite** [comment]
It is upto the maintainer to create rules for his/her project. Not everybody has to follow the same method. Default assignees are set in many different repositories, not only this particular one. Again, if you need to make some enhancements, please open a new issue under feature request category (which does not have default assignees)
